version: 0.2

phases:
  install:
    commands:
      - echo "Khởi động Docker daemon..."
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo 'Đang chờ Docker daemon...'; sleep 1; done"
      - echo "Docker daemon đã được khởi động."
  pre_build:
    commands:
      - echo "Đăng nhập vào Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 654654447255.dkr.ecr.ap-southeast-1.amazonaws.com
      - REPOSITORY_URI=654654447255.dkr.ecr.ap-southeast-1.amazonaws.com/app-frontend
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo "Build Docker image với tag latest..."
      - docker build -t $REPOSITORY_URI:latest .
      - echo "Tag Docker image với tag commit hash..."
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - echo "Docker images đã được build và tag thành công."
  post_build:
    commands:
      - echo "Đẩy Docker image lên Amazon ECR..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Docker images đã được đẩy lên ECR."
      - echo "Tạo file imagedefinitions.json cho frontend..."
      # Thay "app-frontend" nếu tên container trong ECS task definition khác
      - printf '[{"name":"app-frontend","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo "File imagedefinitions.json đã được tạo thành công."

artifacts:
  files:
    - imagedefinitions.json
